version: '3'

services:

  webserver:
    build: 
      context: nginx
    container_name: nginx
    networks:
      - node-network
    tty: true
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    image: mysql:8.0.29
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-network

networks:
  node-network:
    driver: bridge