FROM node:18 AS builder

WORKDIR /usr/src/app
COPY index.js .
RUN npm init -y && npm install express

FROM node:18-alpine

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/ ./
EXPOSE 3000
ENTRYPOINT ["node","index.js"]