FROM node:18 AS builder

WORKDIR /usr/src/app
COPY index.js .
RUN npm init -y && npm install express

FROM node:18-alpine

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/ ./

EXPOSE 3000
ENTRYPOINT ["node","index.js"]

--------------------------funcionando

FROM node:18 

WORKDIR /usr/src/app
COPY index.js .
RUN npm init -y && npm install express
RUN apt-get update && apt-get install -y wget

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

EXPOSE 3000

# CMD ["node","index.js"]
----------------------------------